#cloud-config
# Cloud-init configuration for SIEM platform VMs

# System configuration
hostname: ${hostname}
fqdn: ${hostname}.siem.local
timezone: ${timezone}

# User configuration
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: siem-admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

# Package updates and installation
package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - net-tools
  - unzip
  - jq
  - python3
  - python3-pip
  - docker.io
  - docker-compose
  - ansible
  - fail2ban
  - ufw
  - chrony

# Docker configuration
runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu
  - usermod -aG docker siem-admin
  
  # Configure firewall
  - ufw --force enable
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - ufw allow from 10.0.0.0/8
  - ufw allow from 172.16.0.0/12
  - ufw allow from 192.168.0.0/16
  
  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Configure time synchronization
  - systemctl enable chrony
  - systemctl start chrony
  
  # Create SIEM directories
  - mkdir -p /opt/siem/{config,data,logs,scripts}
  - chown -R siem-admin:siem-admin /opt/siem
  
  # Download SIEM platform scripts
  - wget -O /opt/siem/scripts/install.sh https://raw.githubusercontent.com/siem-platform/installer/main/install.sh
  - chmod +x /opt/siem/scripts/install.sh
  
  # Set up log rotation
  - |
    cat > /etc/logrotate.d/siem << EOF
    /opt/siem/logs/*.log {
        daily
        rotate 30
        compress
        delaycompress
        missingok
        notifempty
        create 644 siem-admin siem-admin
    }
    EOF

# File creation
write_files:
  - path: /etc/sysctl.d/99-siem.conf
    content: |
      # SIEM platform optimizations
      vm.max_map_count=262144
      vm.swappiness=1
      net.core.somaxconn=65535
      net.ipv4.tcp_max_syn_backlog=65535
      fs.file-max=2097152
    permissions: '0644'
  
  - path: /etc/security/limits.d/99-siem.conf
    content: |
      # SIEM platform limits
      * soft nofile 65535
      * hard nofile 65535
      * soft nproc 32768
      * hard nproc 32768
    permissions: '0644'
  
  - path: /opt/siem/config/environment
    content: |
      # SIEM Platform Environment Variables
      SIEM_ENVIRONMENT=${environment}
      SIEM_NODE_TYPE=${node_type}
      SIEM_TENANT_ID=${tenant_id}
      SIEM_CLUSTER_NAME=${cluster_name}
    permissions: '0644'
    owner: siem-admin:siem-admin

# Final commands
final_message: |
  SIEM Platform VM initialization complete!
  
  System Information:
  - Hostname: ${hostname}
  - Timezone: ${timezone}
  - Environment: ${environment}
  
  Next Steps:
  1. Run the SIEM installation script: /opt/siem/scripts/install.sh
  2. Configure services according to your deployment mode
  3. Access the management interface once services are running
  
  For support, visit: https://github.com/siem-platform/docs

