# Ansible Inventory for SIEM Platform

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/siem_platform_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Single Node Deployment
[siem_single_node]
siem-single-node ansible_host={{ single_node_ip }}

# Multi-Tenant Deployment Groups
[wazuh_managers]
{% for i in range(tenant_count) %}
wazuh-manager-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.10 tenant_id={{ i + 1 }}
{% endfor %}

[wazuh_indexers]
{% for i in range(tenant_count) %}
wazuh-indexer-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.11 tenant_id={{ i + 1 }}
{% endfor %}

[graylog_servers]
{% for i in range(tenant_count) %}
graylog-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.20 tenant_id={{ i + 1 }}
{% endfor %}

[mongodb_servers]
{% for i in range(tenant_count) %}
mongodb-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.21 tenant_id={{ i + 1 }}
{% endfor %}

[grafana_servers]
{% for i in range(tenant_count) %}
grafana-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.25 tenant_id={{ i + 1 }}
{% endfor %}

[thehive_servers]
{% for i in range(tenant_count) %}
thehive-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.30 tenant_id={{ i + 1 }}
{% endfor %}

[cortex_servers]
{% for i in range(tenant_count) %}
cortex-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.31 tenant_id={{ i + 1 }}
{% endfor %}

[opencti_servers]
{% for i in range(tenant_count) %}
opencti-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.35 tenant_id={{ i + 1 }}
{% endfor %}

[misp_servers]
{% for i in range(tenant_count) %}
misp-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.36 tenant_id={{ i + 1 }}
{% endfor %}

[velociraptor_servers]
{% for i in range(tenant_count) %}
velociraptor-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.40 tenant_id={{ i + 1 }}
{% endfor %}

[cassandra_servers]
{% for i in range(tenant_count) %}
cassandra-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.50 tenant_id={{ i + 1 }}
{% endfor %}

[praeco_servers]
{% for i in range(tenant_count) %}
praeco-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.60 tenant_id={{ i + 1 }}
{% endfor %}

[shuffle_servers]
{% for i in range(tenant_count) %}
shuffle-tenant-{{ i + 1 }} ansible_host=10.{{ i + 100 }}.1.70 tenant_id={{ i + 1 }}
{% endfor %}

[load_balancers]
siem-load-balancer ansible_host={{ load_balancer_ip }}

# Logical groupings
[wazuh:children]
wazuh_managers
wazuh_indexers

[threat_intel:children]
opencti_servers
misp_servers

[case_management:children]
thehive_servers
cortex_servers

[log_management:children]
graylog_servers
mongodb_servers

[visualization:children]
grafana_servers

[investigation:children]
velociraptor_servers

[alerting:children]
praeco_servers

[automation:children]
shuffle_servers

[databases:children]
mongodb_servers
cassandra_servers

[multi_tenant:children]
wazuh
threat_intel
case_management
log_management
visualization
investigation
alerting
automation
databases

[siem_platform:children]
siem_single_node
multi_tenant
load_balancers

