apiVersion: v2
name: siem-platform
description: A comprehensive SIEM platform Helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: wazuh
    version: "4.7.0"
    repository: "https://wazuh.github.io/wazuh-helm"
    condition: wazuh.enabled
  
  - name: graylog
    version: "2.1.0"
    repository: "https://helm.graylog.org"
    condition: graylog.enabled
  
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  
  - name: redis
    version: "18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

